/** @type {import('next').NextConfig} */
const nextConfig = {
  // Static export: the whole site ships to Netlify's CDN as plain HTML.
  // Host -> officer routing is done by Netlify redirects (see public/_redirects,
  // regenerated by scripts/gen-redirects.mjs), NOT Next middleware.
  output: "export",
  trailingSlash: true,
  images: {
    // required with output: "export" — no Image Optimization server at runtime.
    unoptimized: true,
  },
  eslint: {
    // CI runs lint separately; don't fail the build on it.
    ignoreDuringBuilds: true,
  },
};

export default nextConfig;
